pages:
  - 主页: 'index.md'
  - 目录:
    - GPU Gems3: 'Gems3/intro.md'

markdown_extensions:
  - admonition
  - smarty
  - sane_lists
  - mdx_math

extra_css:
  - css/style.css
  - css/admonition_fix.css

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML'

site_url: https://learnopengl-cn.github.io/

repo_url: https://github.com/LearnOpenGL-CN/LearnOpenGL-CN

site_description: '尝试翻译下《GPU Gems》系列'

site_name: 'alasja翻译小站'

docs_dir: 'docs'

theme: jekyll-theme-slate