pages:
  - 《GPU Gem3》: 'index.md'
  - 《Real Time Renderring》: 'index.md'
  - 杂项: 'code_repo.md'

site_name: 'GraphicT'

site_description: 'alasja的业余玩具'

site_url: https://GraphicT.github.io/

repo_url: https://github.com/alasja/GraphicT.github.io

markdown_extensions:
  - admonition
  - smarty
  - sane_lists
  - mdx_math

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML'

extra_css:
  - css/style.css
  - css/admonition_fix.css

docs_dir: 'docs'

theme_dir: 'yeti'